### PR TITLE
Disable MPRIS listener extension in Windows and macOS

### PR DESCRIPTION
**Pull request by thp**
Based on the discussion in #272.

### CODE REVIEW

**Comment by vossad01** [comment]
I agree that it makes sense to do this.

I have not looked into extensions before, is the following correct?
* `__only_for__`
    Extension only appears if executing ui is in given list
* `__mandatory_in__`
    Extension is enabled and hidden if executing ui is in given list
* `__disable_in__`
    Extension is disabled and hidden if executing ui is in given list

If it is it just struck me that `__only_for__`  and `__disable_in__` provide different ways to do the same thing, such that this could alternatively be `__disable_in__ = 'win32,osx'`.

**Comment by elelay** [comment]
@vossad01 your reasoning is correct. But besides boolean logic, having 2 keywords adds flexibility to express one's intent I guess.

**Comment by vossad01** [comment]
@elelay Does this need to land in `gtk3` too?

**Comment by elelay** [comment]
> Does this need to land in gtk3 too?

Yes, I forgot. Done.

**Pull request merged**
