### PR TITLE
Gtk3 windows installer

### PR DESCRIPTION
**Pull request by elelay**
gPodder 3.10 and later (python3, gtk3) windows support.
Uses msys2 to build the normal and portable installers.
Based on Quodlibet's build tools.

### CODE REVIEW

**Comment by elelay** [comment]
TODO:
 - translations don't work
 - list package versions

**Comment by elelay** [comment]
Installers:
 - [gpodder-3.10.1-installer.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1-installer.exe)
 - [gpodder-3.10.1-portable.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1-portable.exe)

**Comment by elelay** [comment]
New installers:
 - [gpodder-3.10.1_04918713-portable.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1_04918713-portable.exe)
 - [gpodder-3.10.1_04918713-installer.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1_04918713-installer.exe)

**Comment by elelay** [comment]
New installers:
 - [gpodder-3.10.1_dac2d2c0-portable.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1_dac2d2c0-portable.exe)
 - [gpodder-3.10.1_dac2d2c0-installer.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1_dac2d2c0-installer.exe)

**Comment by thp** [comment]
Cool! I'll have a look and give it a try soon.

**Comment by elelay** [comment]
Thanks for the review.
Agreed: the terminfo db should be removed. Sorry, I actually did it in my last commit but didn't upload new installers.

**Comment by elelay** [comment]
I'd like to update the appveyor config in a future PR.

**Comment by elelay** [comment]
New installers + contents:
 - [gpodder-3.10.1_0f78fdc1-portable.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1_0f78fdc1-portable.exe)
 - [gpodder-3.10.1_0f78fdc1-installer.exe](http://croco.elelay.fr/dropbox/gpodder-3.10.1_0f78fdc1-installer.exe)
 - [gpodder-3.10.1_0f78fdc1-contents.txt](http://croco.elelay.fr/dropbox/gpodder-3.10.1_0f78fdc1-contents.txt)

**Pull request merged**
