### PR TITLE
add generic Extras menu contribution extension point

### PR DESCRIPTION
**Pull request by elelay**
gtk2 implementation.

### CODE REVIEW

**Comment by adamvoss** [comment]
I noticed that gPodder needed to be restarted after enabling the extension, before the entry would appear.

The enabling the hello_world extension also causes the following additional logging:

**Comment by adamvoss** [comment]
I tested by installing the Hello World extension (`ln -s share/gpodder/examples/hello_world.py share/gpodder/extensions/`) then enabling it in gPodder preferences.

I did notice that I needed to restart gPodder for the menu entry to appear, though the logging from the extension did activate without restart.  Is needing to restart gPodder expected?  Should we add a note in the extension description or something about this limitation?

**Comment by elelay** [comment]
Good point!
This might also be corrected in code, by calling the relevant hooks upon activation.
It's a bit tricky because `extensions.py` is UI agnostic.

**Comment by elelay** [comment]
I'm implemented dynamic menu loading in #323. Extensions menu items are added in a proper section of the *Extras* menu.

**Comment by elelay** [comment]
also on gtk2 now.

**Comment by adamvoss** [comment]
Thanks for implementing this!  It seems to have some unintended consequences though.  Many extensions will throw an exceptions:
```
1501112378.452013 [gpodder.log] ERROR: Uncaught exception: Traceback (most recent call last):
  File "/home/user/dev/gpodder/src/gpodder/gtkui/desktop/preferences.py", line 413, in on_extensions_cell_toggled
    self.on_extension_enabled(container.module)
  File "/home/user/dev/gpodder/src/gpodder/gtkui/main.py", line 3543, in on_extension_enabled
    extension.on_ui_initialized(self.model,
AttributeError: gPodderExtension instance has no attribute 'on_ui_initialized'
```

because they do not implement `on_ui_initialized`.   The easiest fix would be to check for the existence of the member, but I am definitely open to cleaner solutions.

Additionally, this also causes start-up actions to happen when the extension enables which is perhaps not always desired.  For example enabling "Minimize on start" minimizes the application immediately when enabled.

**Comment by elelay** [comment]
good catch @adamvoss!
Now I check before calling methods.
Regarding minimize on start, I'm tented to add a boolean `isRealStart` to `on_ui_iniatlized` and `on_ui_object_available` but it'll break compatibility. Maybe introduce a new `on_lifecycle` with varying parameters and the `isRealStart` information ? Or a boolean somewhere `realStart` that extensions can check by themselves before doing things meant for startup?

**Comment by elelay** [comment]
Added a new `on_application_started` hook

**Pull request merged**
