### PR TITLE
Build for Mac on Github.

### PR DESCRIPTION
**Pull request by auouymous**

### CODE REVIEW

**Comment by auouymous** [comment]
@computerfreak105, @RodRCode, @Ploddles I had to move the Mac build from CircleCI to Github so it would build. Could one of you try out the artifact at https://github.com/auouymous/gpodder/actions/runs/10257229158 and let me know if it works? The build systems no longer support macos-11, so 12 is now required to use gpodder on Mac.

**Comment by computerfreak105** [comment]
Thanks, this is great! I’ll gladly give it a try. I plan to do it today evening after work.

 

 

Von: auouymous ***@***.***> 
Gesendet: Dienstag, 6. August 2024 02:22
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Mention ***@***.***>
Betreff: Re: [gpodder/gpodder] Build for Mac on Github. (PR #1647)

 

@computerfreak105 <https://github.com/computerfreak105> , @RodRCode <https://github.com/RodRCode> , @Ploddles <https://github.com/Ploddles>  I had to move the Mac build from CircleCI to Github so it would build. Could one of you try out the artifact at https://github.com/auouymous/gpodder/actions/runs/10257229158 and let me know if it works? The build systems no longer support macos-11, so 12 is now required to use gpodder on Mac.

**Comment by Ploddles** [comment]
> @computerfreak105, @RodRCode, @Ploddles I had to move the Mac build from CircleCI to Github so it would build. Could one of you try out the artifact at https://github.com/auouymous/gpodder/actions/runs/10257229158 and let me know if it works? The build systems no longer support macos-11, so 12 is now required to use gpodder on Mac.

I still get the ffmpeg error if the video formats aren't all set at 360p.

**Comment by auouymous** [comment]
@Ploddles After I get the build working, I will add a setting to specify custom PATHs so it can find ffmpeg. I just need to know if everything in this build works because it has a new bundle of libraries and is now built on a different platform.

**Comment by Ploddles** [comment]
Apart from having to set everything to 360p, yes, everything seems to work for me. Thanks.

**Comment by computerfreak105** [comment]
Works great for me so far, thank you :-)

 

 

 

Von: auouymous ***@***.***> 
Gesendet: Dienstag, 6. August 2024 02:22
An: gpodder/gpodder ***@***.***>
Cc: computerfreak105 ***@***.***>; Mention ***@***.***>
Betreff: Re: [gpodder/gpodder] Build for Mac on Github. (PR #1647)

 

@computerfreak105 <https://github.com/computerfreak105> , @RodRCode <https://github.com/RodRCode> , @Ploddles <https://github.com/Ploddles>  I had to move the Mac build from CircleCI to Github so it would build. Could one of you try out the artifact at https://github.com/auouymous/gpodder/actions/runs/10257229158 and let me know if it works? The build systems no longer support macos-11, so 12 is now required to use gpodder on Mac.

**Comment by auouymous** [comment]
Thanks for testing.

@Ploddles Can you test #1649 for me? There is now a "release from macos" link at the bottom of PRs to download an artifact. You can open preferences, click "edit config", search for "path.alt" and add the directory your ffmpeg binary is in. Restart gpodder, and if the PR works, yt-dlp should be able to see ffmpeg.

**Comment by Ploddles** [comment]
> Thanks for testing.
> 
> @Ploddles Can you test #1649 for me? There is now a "release from macos" link at the bottom of PRs to download an artifact. You can open preferences, click "edit config", search for "path.alt" and add the directory your ffmpeg binary is in. Restart gpodder, and if the PR works, yt-dlp should be able to see ffmpeg.

YES, it works. On the first download of a video the system pops up a message about allowing gPodder to access ffmpeg but you only need to do it the once. I've just successfully downloaded a couple of videos at 1080p 🥇 
If you update ffmpeg then it pops up the message again but just click to allow again and it works.

**Pull request merged**
