### PR TITLE
Add contributing.md

### PR DESCRIPTION
**Pull request by ColdIce1**
See on-going issue #1150

### CODE REVIEW

**Comment by elelay** [comment]
Seems good. Maybe add `make lint unittest` before push.
They in turn need `pip3 install pytest-cov minimock pycodestyle isort requests pytest pytest-httpserver`

**Comment by ColdIce1** [comment]
Can I suggest we adding a development.txt for easy pip install in that case? :)

**Comment by elelay** [comment]
yes, linting and unittests are done on the PR. 
I still recommend running `make lint unittest` because it's then easier to fix all errors in one go instead of 1 commit per try if one uses only the CI.

**Comment by elelay** [comment]
Merged, thanks :-)

**Pull request merged**
