### PR TITLE
Fix #796 MKV Files Not Properly Renamed

### LINKED ISSUE #796: MKV Files Not Properly Renamed
Using the following GPodder options, MKV files that are downloaded are not renamed properly.

1. Youtube-dl extension is in use with the "bestvideo+bestaudio" option.
2. Rename Episodes extension is in use.

If an MP4 or WEBM file is downloaded, the renaming works properly.  If an MKV file is downloaded it is not renamed and a zero-byte MP4 file is created that *is* properly named.

I don't have example video links available right now but will have them in a day or two.

### PR DESCRIPTION
**Pull request by elelay**
Try known youtube-dl extensions in case it changed it.
eg. when downloading mp4 video + opus audio it need to combine it in an mkv container.

### CODE REVIEW

**Comment by elelay** [comment]
@auouymous it fixes the issue. Do you agree?

**Comment by auouymous** [comment]
That fixes the issue with MKV files, but they get a WEBM or MP4 extension, depending on video format. Another issue is that the first download has an unknown ext and uses .bin.partial which gets renamed in download.py. If the file is deleted, format changed and episode is re-downloaded, the newly downloaded file keeps the previous extension.

Could retrieve_resume() return a new tempname and the filename in episode be updated with it? The youtube-dl extension could strip the extension from tempname, leaving .partial. If that tempname exists, it inserts dot_ext in returned_tempname and renames the file. Otherwise it uses the code in this patch to find the file and inserts try_ext in returned_tempname and renames the file. That way the files on disk have the correct extension.

Should MAX_FILENAME_WITH_EXT_LENGTH in model.py account for the extra extension youtube-dl can append after .partial? ".webm" would be the longest.

**Comment by elelay** [comment]
Thanks for your comments!

> That fixes the issue with MKV files, but they get a WEBM or MP4 extension, depending on video format.
Another issue is that the first download has an unknown ext and uses .bin.partial which gets renamed in download.py. If the file is deleted, format changed and episode is re-downloaded, the newly downloaded file keeps the previous extension.

Yes: it's annoying.

> Could retrieve_resume() return a new tempname and the filename in episode be updated with it?

We'll have to make it work with autodetected resume at startup...

> Should MAX_FILENAME_WITH_EXT_LENGTH in model.py account for the extra extension youtube-dl can append after .partial? ".webm" would be the longest.

ah, yes, good point.

**Comment by elelay** [comment]
bc5327d converts the episode extension to .mkv if necessary by returning the mimetype associated to the extension chosen by youtubeDL and ensuring it's used in `download.py`.
I think using the new mimetype in download.py was intented, but inadvertently broken at some point by refactoring `episode.extension()` and `episode.local_filename()`.

**Comment by auouymous** [comment]
That works.

**Pull request merged**
