### PR TITLE
Update tagging.py

### PR DESCRIPTION
**Pull request by AntonelloA**
Added "subtitle" tag to audio podcasts, taken from podcast "episode.description".
To see the change in action, try (before and after) one of the episodes of this podcast: 
http://www.radio.rai.it/radio2/podcast/rssradio2.jsp?id=80

### CODE REVIEW

**Comment by AntonelloA** [comment]
It need the "mutagen" Python module in \gPodder\lib\python3.7

**Comment by elelay** [comment]
Hi @AntonelloA, this looks good, sorry not to merge it sooner.
I'll get back to it when I have time !
Thanks,

**Comment by AntonelloA** [comment]
> Hi @AntonelloA, this looks good, sorry not to merge it sooner.
> I'll get back to it when I have time !
> Thanks,

No problem!
Thanks
Antonello

**Comment by AntonelloA** [comment]
> Hi @AntonelloA, this looks good, sorry not to merge it sooner.
> I'll get back to it when I have time !
> Thanks,
Do you think it's possible to have the "mutagen" folder in \gPodder\lib\python3.7 directly during setup? Now you have to put it there manually, taking the folder from github (I had to experiment a little before knowing what to copy and where to put it).
Thanks
Antonello

**Comment by elelay** [comment]
> Do you think it's possible to have the "mutagen" folder in \gPodder\lib\python3.7 directly during setup? 
What version are you using? mutagen should be installed on windows and macOS bundles, but maybe there is a regression.

**Comment by AntonelloA** [comment]
> > Do you think it's possible to have the "mutagen" folder in \gPodder\lib\python3.7 directly during setup?
> 
> What version are you using? mutagen should be installed on windows and macOS bundles, but maybe there is a regression.

I'm using the latest Windows version, and for the last 3-4 version upgrades I had to manually put the mutagen folder into \gPodder\lib\python3.7, every time after setup, along with my edited copy of tagging.py. 
I'm not an expert of Python, and after a bit of trial-and-error I found that this extension needs the "mutagen" folder inside \gPodder\lib\python3.7

**Comment by elelay** [comment]
Strange: from a fresh gPodder 3.10.11 windows installer I can activate the tagging extension without manually copying mutagen (and it works).
It's only bundled with gPodder since 3.10.9, so maybe you copy it manually because it was required in earlier versions?

**Comment by AntonelloA** [comment]
> Strange: from a fresh gPodder 3.10.11 windows installer I can activate the tagging extension without manually copying mutagen (and it works).
> It's only bundled with gPodder since 3.10.9, so maybe you copy it manually because it was required in earlier versions?

I'll let you know about this problem after the next update.
Thanks
Antonello

**Pull request merged**
