### PR TITLE
Remove ubuntu appindicator/unity extensions

### LINKED ISSUE #767: Remove Unity/Appindicator support?
Hi,
I tried running git master branch on Ubuntu 20.04 and get the following error message for the `ubuntu_appindicator` extension
```
1585397262.349251 [gpodder.extensions] ERROR: Cannot load ubuntu_appindicator from /home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_appindicator.py: cannot import name AppIndicator3, introspection typelib not found
Traceback (most recent call last):
  File "/home/bernd/Development/gpodder/gpodder/src/gpodder/extensions.py", line 260, in set_enabled
    self.load_extension()
  File "/home/bernd/Development/gpodder/gpodder/src/gpodder/extensions.py", line 302, in load_extension
    module_file = imp.load_module(basename, fp, self.filename,
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_appindicator.py", line 8, in <module>
    from gi.repository import AppIndicator3 as appindicator
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 132, in load_module
    raise ImportError('cannot import name %s, '
ImportError: cannot import name AppIndicator3, introspection typelib not found
```
And the following error message for `ubuntu_unity` extension
```
1585397262.353139 [gpodder.extensions] ERROR: Cannot load ubuntu_unity from /home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_unity.py: [Errno 2] No such file or directory: 'python'
Traceback (most recent call last):
  File "/home/bernd/Development/gpodder/gpodder/src/gpodder/extensions.py", line 264, in set_enabled
    self.module.on_load()
  File "/home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_unity.py", line 45, in on_load
    self.process = util.Popen(['python', __file__],
  File "/home/bernd/Development/gpodder/gpodder/src/gpodder/util.py", line 2028, in __init__
    super(Popen, self).__init__(*args, **kwargs)  # Python 2 syntax
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'
```
or the following error meesage if i change `python` to `python3`
```
/home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_unity.py:61: PyGIWarning: Unity was imported without specifying a version first. Use gi.require_version('Unity', '7.0') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, GObject
/home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_unity.py:99: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
  GObject.threads_init()
/home/bernd/Development/gpodder/gpodder/share/gpodder/extensions/ubuntu_unity.py:100: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  loop = GObject.MainLoop()
```

In bin/gpodder there is the following check
```
gpodder.ui.unity = (os.environ.get('DESKTOP_SESSION', 'unknown').lower() in
                    ('ubuntu', 'ubuntu-2d'))
```
which assumes that a desktop session "ubuntu" is using unity. But Ubuntu has been using Gnome Shell for some time now and asking for the DESKTOP_SESSION just returns `ubuntu`
```
>>> import os
>>> os.environ.get('DESKTOP_SESSION', 'unknown').lower()
'ubuntu'
```

So could we just remove the `gpodder.ui.unity` flag and the two extensions?
* ubuntu_appindicator
* ubuntu_unity

### PR DESCRIPTION
**Pull request by brot**
GNOME Shell replaced Unity in Ubuntu 17.10, so the `ubuntu_unity`
extension does not work anymore.
Also `ubuntu_appindicator` can be removed, because GNOME Shell does not
include AppIndicator anymore and so it does not work anymore too.

Closes #767

### CODE REVIEW

**Comment by auouymous** [comment]
I don't use ubuntu, unity or gnome, but what version of ubuntu removed unity? Three days ago, someone with 18.04 manually upgraded to latest gpodder to fix an issue. Would this change remove functionality for anyone still using 18.04 if they upgraded to the next release of gpodder?

I would recommend against removing support until any LTS versions that use unity become EOL, and 18.04 is good until apr2023.

**Comment by brot** [comment]
> I don't use ubuntu, unity or gnome, but what version of ubuntu removed unity? Three days ago, someone with 18.04 manually upgraded to latest gpodder to fix an issue. Would this change remove functionality for anyone still using 18.04 if they upgraded to the next release of gpodder?
> 
> I would recommend against removing support until any LTS versions that use unity become EOL, and 18.04 is good until apr2023.

16.04 was the last LTS with Unity. Ubuntu 18.04 was the first LTS with GNOME-Shell. But yes, you're right. 16.04 is still not EOL. But it's also annoying that all Ubuntu users using 17.10-20.04 (all versions with GNOME shell) getting this error message. 

So I'm looking for a way to check if Unity or Gnome Shell is running on Ubuntu

**Comment by brot** [comment]
So #769 should remove the errors for newer Ubuntu versions. Sadly I don't have any Ubuntu 16.04 installation to test if this still works on Unity.

**Comment by elelay** [comment]
Closing in favor of #776.

**Pull request closed without merging**
