### PR TITLE
fix incorrectly sorted imports shown by make lint

### PR DESCRIPTION
**Pull request by auouymous**
Travis CI doesn't appear to fail for these but my local isort 4.2.5 with python 3.6 does.

### CODE REVIEW

**Comment by auouymous** [comment]
It appears make lint is using python 2.7 and that might be causing the difference in errors. Is it possible to force make lint to use python3 instead of the system default?

**Comment by elelay** [comment]
My system's default python is python3 and I have isort 4.3.21 installed.
I don't get any import order error.

**Comment by elelay** [comment]
make lint runs `isort -rc -c share src/gpodder tools bin/* *.py`. Depending on your install, `isort` will use whichever python it is configured to.
eg. on my system I have isort in /usr/bin, from the ArchLinux package `extra/python-isort`. Its first line is `#!/usr/bin/python` (which is python 3.8.1).
Do you propose we use `python3 $(which isort)` in the makefile?

**Comment by auouymous** [comment]
First line of /usr/bin/isort on Gentoo is `#!/usr/bin/python-exec2c`. I tried calling isort with `python3 $(which isort)` but `$(which isort)` returns nothing inside the makefile (it returns /usr/bin/isort outside). Calling isort with `python3 /usr/bin/isort` does properly use python 3.6.

I am also able to install isort without python 2.7 support and it properly uses python 3.6. However, that and `python3 /usr/bin/isort` both produce the following errors (isort 4.2.5):

```
ERROR: /home/gpodder/git/src/gpodder/model.py Imports are incorrectly sorted.
ERROR: /home/gpodder/git/src/gpodder/my.py Imports are incorrectly sorted.
```

Upgrading to 4.3.15 or 4.3.21_p2 produces these errors:

```
ERROR: /home/gpodder/git/src/gpodder/feedcore.py Imports are incorrectly sorted.
ERROR: /home/gpodder/git/src/gpodder/model.py Imports are incorrectly sorted.
ERROR: /home/gpodder/git/src/gpodder/my.py Imports are incorrectly sorted.
```

Getting $(which isort) to work would be the first step to ensuring python3 is used in make lint for anyone who has python 2.7 as primary. But there is a bigger problem with isort that causes inconsistencies.

The full errors for those files are:

```
ERROR: /home/gpodder/git/src/gpodder/feedcore.py Imports are incorrectly sorted.
--- /home/gpodder/git/src/gpodder/feedcore.py:before    2020-02-03 19:34:45
+++ /home/gpodder/git/src/gpodder/feedcore.py:after     2020-02-04 15:38:39.157423
@@ -28,6 +28,7 @@
 from urllib.error import HTTPError
 
 import podcastparser
+
 from gpodder import util
 
 logger = logging.getLogger(__name__)
ERROR: /home/gpodder/git/src/gpodder/model.py Imports are incorrectly sorted.
--- /home/gpodder/git/src/gpodder/model.py:before       2020-02-03 17:54:01
+++ /home/gpodder/git/src/gpodder/model.py:after        2020-02-04 15:38:39.193906
@@ -35,8 +35,9 @@
 import string
 import time
 
+import podcastparser
+
 import gpodder
-import podcastparser
 from gpodder import (coverart, escapist_videos, feedcore, registry, schema,
                      util, vimeo, youtube)
 
ERROR: /home/gpodder/git/src/gpodder/my.py Imports are incorrectly sorted.
--- /home/gpodder/git/src/gpodder/my.py:before  2020-02-03 19:34:45
+++ /home/gpodder/git/src/gpodder/my.py:after   2020-02-04 15:38:39.211328
@@ -32,12 +32,13 @@
 import sys
 import time
 
-import gpodder
 # Append gPodder's user agent to mygpoclient's user agent
 import mygpoclient
-from gpodder import minidb, util
 from mygpoclient import api, public
 from mygpoclient import util as mygpoutil
+
+import gpodder
+from gpodder import minidb, util
 
 _ = gpodder.gettext
 
```

Adding podcastparser and mygpoclient to known_first_party in setup.cfg fixes the errors in isort 4.3+ but changes last error in 4.2.5 to:

```
ERROR: /home/gpodder/git/src/gpodder/my.py Imports are incorrectly sorted.
--- /home/gpodder/git/src/gpodder/my.py:before  2020-02-03 19:34:45
+++ /home/gpodder/git/src/gpodder/my.py:after   2020-02-04 16:07:39.008552
@@ -36,8 +36,8 @@
 # Append gPodder's user agent to mygpoclient's user agent
 import mygpoclient
 from gpodder import minidb, util
+from mygpoclient import util as mygpoutil
 from mygpoclient import api, public
-from mygpoclient import util as mygpoutil
 
 _ = gpodder.gettext
 
```

**Comment by elelay** [comment]
> Adding podcastparser and mygpoclient to known_first_party in setup.cfg fixes the errors in isort 4.3+ but changes last error in 4.2.5 to

They are third-party not first-party, so we should add them to third_party. Looking at setup.cfg I don't remember why soco is first_party in the first place.

Here are the errors I get after I add podcastparser and mygpoclient to third_party:
```
ERROR: /home/elelay/devel/gPodder/src/gpodder/model.py Imports are incorrectly sorted.
--- /home/elelay/devel/gPodder/src/gpodder/model.py:before	2020-01-05 17:46:01.122082
+++ /home/elelay/devel/gPodder/src/gpodder/model.py:after	2020-02-05 08:27:27.153737
@@ -35,8 +35,9 @@
 import string
 import time
 
+import podcastparser
+
 import gpodder
-import podcastparser
 from gpodder import (coverart, escapist_videos, feedcore, registry, schema,
                      util, vimeo, youtube)
 
ERROR: /home/elelay/devel/gPodder/src/gpodder/feedcore.py Imports are incorrectly sorted.
--- /home/elelay/devel/gPodder/src/gpodder/feedcore.py:before	2020-02-05 08:27:21.239610
+++ /home/elelay/devel/gPodder/src/gpodder/feedcore.py:after	2020-02-05 08:27:27.174436
@@ -28,6 +28,7 @@
 from urllib.error import HTTPError
 
 import podcastparser
+
 from gpodder import util
 
 logger = logging.getLogger(__name__)
ERROR: /home/elelay/devel/gPodder/src/gpodder/my.py Imports are incorrectly sorted.
--- /home/elelay/devel/gPodder/src/gpodder/my.py:before	2020-01-04 12:24:35.096508
+++ /home/elelay/devel/gPodder/src/gpodder/my.py:after	2020-02-05 08:27:27.194055
@@ -32,12 +32,13 @@
 import sys
 import time
 
-import gpodder
 # Append gPodder's user agent to mygpoclient's user agent
 import mygpoclient
-from gpodder import minidb, util
 from mygpoclient import api, public
 from mygpoclient import util as mygpoutil
+
+import gpodder
+from gpodder import minidb, util
 
 _ = gpodder.gettext
 
```

They seem reasonable changes

**Comment by auouymous** [comment]
Adding those to third_party along with your patch works for travis CI and fixes the issue for isort 4.3+ but 4.2.5 still has this error:

```
ERROR: /home/gpodder/git/src/gpodder/my.py Imports are incorrectly sorted.
--- /home/gpodder/git/src/gpodder/my.py:before  2020-02-05 00:36:55
+++ /home/gpodder/git/src/gpodder/my.py:after   2020-02-05 00:45:13.096962
@@ -34,8 +34,8 @@
 
 # Append gPodder's user agent to mygpoclient's user agent
 import mygpoclient
+from mygpoclient import util as mygpoutil
 from mygpoclient import api, public
-from mygpoclient import util as mygpoutil
 
 import gpodder
 from gpodder import minidb, util
```

**Comment by elelay** [comment]
Maybe you could create a virtualenv and install an updated isort in it?

**Comment by elelay** [comment]
Thanks for updated changes. I'm ready to merge the branch if it's ok for you.

**Comment by auouymous** [comment]
Gentoo has isort 4.2.5 marked as stable but I can tell it to install any version. If the makefile needs a specific version it should either check and fail or do the virtual install itself (I don't know how to make that change), otherwise another developer might run into the same problem. A quick search suggests virtualenv might be python 3, so the python 2.7 issue might need to be fixed first.

I am fine with you merging, should I open issues for `python3 $(which isort)` and requiring/installing a specific isort version?

**Comment by elelay** [comment]
> Gentoo has isort 4.2.5 marked as stable but I can tell it to install any version. 

from https://packages.gentoo.org/packages/dev-python/isort isn't 4.3.15 also stable? Maybe they have 4.2.x for python2 and 4.3.x for python3.

> If the makefile needs a specific version it should either check and fail

with the end of python2 support, I guess the odds are pretty odd. On the other hand it did happen to you... I don't have time for implementing this myself but wouldn't object if you did (isort is not helping because it shows a giant banner with the version when invoking `isort --version`).

> should I open issues for python3 $(which isort) and requiring/installing a specific isort version?

not to my mind. I was asking if it was what you wanted.

**Comment by auouymous** [comment]
> from https://packages.gentoo.org/packages/dev-python/isort isn't 4.3.15 also stable?

It is stable on the 2 green platforms.


> isort is not helping because it shows a giant banner with the version when invoking `isort --version`).

I noticed that too.

**Pull request merged**
