### PR TITLE
fix #159 - gtk3: Empty tree views do not indicate why

### LINKED ISSUE #159: gtk3: Empty tree views do not indicate why
**On gtk2,** 
On the Podcasts tab,
the main GtkTreeView will say (centered text) "Loading..." when the application has launched but before the list of episodes has been populated.
I believe there may be different text when it has completed loading but no episodes were found.

On the Progress tab,
The GtkTreeView will say "No active tasks" when it has an empty queue.

**On gtk3,**
The GtkTreeView on both tabs does not have any text, thus users do not know whether they are still waiting on loading or if it is correctly blank.

### PR DESCRIPTION
**Pull request by elelay**

### CODE REVIEW

**Comment by vossad01** [comment]
Thanks for working on this!  This seems to fix the "Progress" tab, but the Podcast tab still showed blank in my testing.

GTK2:
screenshot from 2017-04-23 11-00-54

GTK3:
screenshot from 2017-04-23 11-03-32

**Comment by elelay** [comment]
Strange: it works for me.
From an empty GPODDER_HOME, ArchLinux, gtk3 3.22.10-1, default theme.

show_empty

**Comment by elelay** [comment]
Same with `en_US.utf8` locale.
Any stack trace?

**Comment by vossad01** [comment]
Sorry my bad.  Midway through I switched to a different (slower) box to better confirm this and after working around #248 I accidentally switched back to `gtk3` rather than this PR.

**Comment by elelay** [comment]
No worries :-)

**Pull request merged**
