### PR TITLE
Add codespell to linter.

### PR DESCRIPTION
**Pull request by auouymous**

### CODE REVIEW

**Comment by elelay** [comment]
so not a single spelling error?

**Review by elelay — APPROVED** [review]

**Comment by auouymous** [comment]
There were many spelling errors before @luzpaz and I fixed them. It won't however catch spelling mistakes in the translations.

**Comment by luzpaz** [comment]
I used `codespell -q 3 -S *.po -L bloc,extracter,parms`  
You might want to consider adding the `-L` flagged words to avoid false positives.

**Comment by auouymous** [comment]
@luzpaz I fixed 'bloc', 'extracter' and 'parms'. I also fixed a couple other issues it found. It currently reports no issues, or is that not the case for you on current git?

**Comment by elelay** [comment]
Oh, sorry. Thanks @luzpaz and @auouymous for the great work!

**Comment by luzpaz** [comment]
> I fixed 'bloc', 'extracter' and 'parms'. I also fixed a couple other issues it found. It currently reports no issues, or is that not the case for you on current git?

Didn't check. If you fixed them then my comment is obsolete. :+1:

**Pull request merged**
