### PR TITLE
Gtk UI: Use a TextView for dialogs with multiple text lines

### PR DESCRIPTION
**Pull request by thp**
Also fixes the secondary text formatting in the normal message dialog.

### CODE REVIEW

**Comment by thp** [comment]
Before:

Screenshot from 2021-08-18 20-12-02

After:

Screenshot from 2021-08-18 20-20-26

**Comment by auouymous** [comment]
The OK button should have default focus.

**Comment by thp** [comment]
Updated PR, the OK button now has default focus, and pressing Enter discards the dialog.

**Comment by auouymous** [comment]
LGTM, thanks!

**Pull request merged**
