### PR TITLE
Add option to rename_download.py to put the sortdate after the podcast title

### PR DESCRIPTION
**Pull request by tkurtbond**
I find it very useful to have the option when renaming download files to put the sortdate after the podcast title.  This allows me to easily sort by podcast and then date within podcast.

### CODE REVIEW

**Comment by auouymous** [comment]
The code looks good but that comment needs two spaces before the `#`. Try running `make lint` to see why.

I assume gpodder uses title by default for filenames and this extension gives you the option to use {title}.ext, {date}.ext or {date}-{title}.ext. And this patch also allows {title}-{date}.ext, correct?

**Comment by tkurtbond** [comment]
> The code looks good but that comment needs two spaces before the `#`. Try running `make lint` to see why.

Done.
 
> I assume gpodder uses title by default for filenames and this extension gives you the option to use {title}.ext, {date}.ext or {date}-{title}.ext. And this patch also allows {title}-{date}.ext, correct?

Yes, that is correct.

**Comment by auouymous** [comment]
Thanks for the patch.

**Comment by tkurtbond** [comment]
> Thanks for the patch.

You are welcome!

**Pull request merged**
