### PR TITLE
rename youtube-dl partial file when it contains % or $ characters

### LINKED ISSUE #837: youtube-dl download with dollar symbol in the title results in 0-byte files
A recent post on [Jim Sterling's YouTube feed](https://www.youtube.com/feeds/videos.xml?channel_id=UCWCw2Sd7RlYJ2yuNVHDWNOA) included a dollar character in the video name. The file created by gPodder is named:
`NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4`

However, when the youtube-dl extension is used to manage the download, the "partial" file is named differently:
`NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial.webm`

Note that the dollar symbol has doubled up. It seems this makes gPodder not able to locate the file to move over to the final file location once the download is complete.

The next time gPodder starts, I get the message:
> [gpodder.common] WARNING: Partial file without episode: /home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial

at which point the file is deleted, leaving only the zero-byte placeholder file.

--

Workaround:
Preventing youtube-dl from managing downloads (`extensions.youtube-dl.manage_downloads: false`) avoids this issue.

FWIW, the youtube-dl command line executable names the file correctly, with only a single dollar sign.

--

System:
Debian Testing
gPodder 3.10.16 (from Debian repos)
youtube-dl 2020.06.16.1-1 (from Debian repos)

### PR DESCRIPTION
**Pull request by auouymous**
Fixes #837

### CODE REVIEW

**Comment by romlok** [comment]
Hi, thanks for looking into this.

I just checked out this branch and ran `./bin/gpodder`. I still get two partial files; the first has the video, the second is zero bytes:

`NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial.webm`
`NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial`

The client outputs the following error to the console for the episode:

```[gpodder.download] ERROR: No such file or directory while downloading "NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About "Value"": /home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial
Traceback (most recent call last):
  File "/data/src/gpodder/src/gpodder/download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "/data/src/gpodder/share/gpodder/extensions/youtube-dl.py", line 88, in retrieve_resume
    os.rename(outtmpl, tempname)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial' -> '/home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial'
```

Looks like it's missing the `.webm` extension on the source file.

**Comment by auouymous** [comment]
Can you change to the 720p MP4 format and see if it works? It might still be using the system installed extension. But if the MP4 works, it could be related to #796.

**Comment by auouymous** [comment]
I just noticed the error shows it is using the fixed extension, but testing the MP4 format will determine if #796 is breaking this.

**Comment by romlok** [comment]
Just tested with 720p mp4 and, yes, it worked as it should, thanks! :+1:

**Comment by auouymous** [comment]
Updated patch works with webm or mp4.

**Comment by romlok** [comment]
I can confirm that the new version works when I have a webm format chosen. The resulting file has a .mp4 extension, rather than .webm, but can be played normally so I don't know if that's intended.

However, it seems to now not work for _some_ mp4 formats, eg:
If I select "MP4 480p (854x480) youtube-dl" it works.
If I select "MP4 720p (1280x720)" it fails:

```
[gpodder.download] ERROR: No such file or directory while downloading "NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About "Value"": /home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial.mp4
Traceback (most recent call last):
  File "/data/src/gpodder/src/gpodder/download.py", line 863, in run
    headers, real_url = downloader.retrieve_resume(self.tempname, self.status_updated)
  File "/data/src/gpodder/share/gpodder/extensions/youtube-dl.py", line 89, in retrieve_resume
    os.rename(outtmpl + '.{}'.format(res['ext']), tempname)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $$69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial.mp4' -> '/home/mel/gPodder/Downloads/Jim Sterling/NBA 2K21 Is $69.99 On Next-Gen Consoles While 2K Spews Vague Nonsense About _Value_.mp4.partial'
```
In this case, the actual source file ends with just `.mp4.partial`, rather than `.mp4.partial.mp4`.

**Comment by auouymous** [comment]
New patch fixes it. The mp4 extension on webm files is related to #796, download a file as webm that doesn't contain $ or %, and it will have the mp4 extension.

**Comment by romlok** [comment]
Confirmed! With the latest commit all the test cases I ran through downloaded and renamed successfully. :+1:

**Comment by elelay** [comment]
Merged, thanks!

**Pull request merged**
