### PR TITLE
Show channel or episode titles in delete dialog

### PR DESCRIPTION
**Pull request by auouymous**
Provides a second, and better, indicator of which channel or episode is being deleted. Only 8 titles up to 60 characters each are shown to avoid excessively large dialogs.

The titles can blend with the final delete message. Should the final message be bold? Or should titles have a prefix such as '• '?

Should the 8 and 60 be adjusted? The dialog appears to self limit its width (wrapping lines), and 4-5@120 would allow fewer double line titles to be shown. It is less likely someone would read more than 4-5 titles when mass deleting, and showing more of long titles might be better.

### CODE REVIEW

**Comment by elelay** [comment]
looks good :+1:

**Comment by auouymous** [comment]
I think it looks better without the blank lines between each title and doesn't drown out the message.

@elelay Does it still look good to you?

**Comment by elelay** [comment]
yes, it's clearer now :+1:

**Comment by elelay** [comment]
Cherry-picked commits because merge seemed overly complex

**Comment by elelay** [comment]
Thanks

**Pull request closed without merging**
