### PR TITLE
Discard episode when its GUID collides with a newer episode.

### LINKED ISSUE #847: Some podcast episodes aren't saved to database
On Windows 10, using gPodder 3.10.16, portable version.

After adding http://www.emptysea.net/tote/podcast1.xml to gPodder (first run, new database), all episodes (currently ~101) are correctly shown in the GUI. However, after restarting gPodder only 22 (in no particular order) are visible in the episodes list. Other feeds can be added and are displayed properly without issues.

The log lists the same error for each missing episode (only the object address changes):

`[gpodder.dbsqlite] ERROR: Cannot save <gpodder.gtkui.model.GEpisode object at 0x04736918>: UNIQUE constraint failed: episode.podcast_id, episode.guid`
`Traceback (most recent call last):`
`  File "C:\apps\gpodder-3.10.16-portable\data\lib\python3.8\site-packages\gpodder\dbsqlite.py", line 214, in _save_object`
`    cur.execute(sql, values)`
`sqlite3.IntegrityError: UNIQUE constraint failed: episode.podcast_id, episode.guid`

### PR DESCRIPTION
**Pull request by auouymous**
This prevents broken feeds from causing broken behavior in gpodder. Fixes #847.

### CODE REVIEW

**Comment by auouymous** [comment]
**Don't merge this yet.** I need to setup a test feed and verify it doesn't break anything if a new episode has the same GUID as an older downloaded episode.

**Comment by auouymous** [comment]
The database exception only happens when multiple new episodes share a GUID, and do not share a GUID with an existing episode. All new episodes with the same GUID as an existing episode become updates for it, but the old episode details eventually overwrite the updates from newer episodes due to sorting newest to oldest. It basically discards all newer episodes and there was no way to get newer enclosures.

With this patch, the old episode keeps the updates from newer episodes, because the old episode is discarded. A downloaded file on the old episode is now "transfered" to the "new" episode. This has no impact if enclosure was used as GUID (both share the same enclosure). But if the new episode has a different enclosure, the episode must be deleted and re-downloaded to get the new enclosure. Of course no users will know this is possible, so this appears to discard old episodes but keeps their downloaded files.

The new patch behavior should be okay since it fixes the database error and other issues related to it, while informing the user about the discarded episodes.

**Comment by elelay** [comment]
Seems correct to me. Ready to merge?

**Comment by auouymous** [comment]
Yes.

**Comment by elelay** [comment]
Merged, thanks!

**Pull request merged**
