### PR TITLE
Update de.po

### PR DESCRIPTION
**Pull request by TZocker**
Update to gPodder 3.10.3

### CODE REVIEW

**Comment by elelay** [comment]
Merged, thanks!

**Comment by elelay** [comment]
There are still a few "fuzzy" translations in de.po. Any chance you might translate them also?

**Comment by TZocker** [comment]
@elelay Perhabs but I have to search them. To see where the Problem is (context).

greetz

**Comment by elelay** [comment]
OK. Feel free to ask if you have any question ;-)

**Comment by TZocker** [comment]
https://github.com/gpodder/gpodder/compare/master...TZocker:patch-2

**Pull request merged**
