### PR TITLE
Create context menus from GMenuModel

### PR DESCRIPTION
**Pull request by tpikonen**
A remix of / alternative to #1293. Add action definitions for context menu items and create context menus (just for channels, for now) from `menus.ui`.

### CODE REVIEW

**Comment by elelay** [comment]
From a quick glance I don't see any drawback to this. Are there?

**Comment by auouymous** [comment]
@elelay Did you look at the channel context menu? The icons are indented, and their text doesn't align with items that lack icons.

**Comment by elelay** [comment]
> @elelay Did you look at the channel context menu? The icons are indented, and their text doesn't align with items that lack icons.

Indeed. On the other hand icons are not visible for me with the master branch.

**Comment by auouymous** [comment]
Oh right, gtk3 defaults to `gtk-menu-images = 0`, setting it to `1` in gtk-3.0 settings.ini enables them. And `gtk-button-images = 1` enables button icons.

**Comment by tpikonen** [comment]
Two releases have now been made after this PR and #1293 were proposed. Merging the context menu changes to the GMenuModel based menus used in the adaptive branch is starting to feel like useless busywork.

Could we move the master branch to GMenuModels, either by merging this or #1293? I can bring this PR up to date and finish the implementation if there's a consensus on merging this.

For reference, here are screenshots of how the channel context menu before and after:

Before:

context-menu-orig

After:

context-menu-new

**Comment by elelay** [comment]
ok from me but I defer to @auouymous decision

**Comment by auouymous** [comment]
I don't like the indented icons. Can this use the verb-icons like popovers? We could remove the indented icons and add verb-icons at the top for the most common actions.

The popovers lack any of the flaws that normal context menus have but @elelay didn't like them (https://github.com/gpodder/gpodder/pull/1293#issuecomment-1214435466) so they are out.

**Comment by tpikonen** [comment]
Ok, I dove into GTK docs and sources and here's what I found:

 * The `verb-icon` attributes are used only in GtkPopovers. GtkMenus ignore it, so they cannot have horizontal button rows.
 * The non-indented icons are a feature of the deprecated GtkImageMenuItem, which is what gPodder currently uses. The GMenuModel based menus are composed of GtkModelMenuItems which can have both a check box (determined from the action type) and an icon (from the `icon` attribute), so this way all the icons will be aligned.

So, with GMenuModels the context menu will either be a GtkMenu with indented icons, or a GtkPopover with icons only in the horizontal button rows. I'm fine with either, but would also prefer the popovers.

**Comment by elelay** [comment]
Thanks for looking into it.

@auouymous @tpikonen you are both convinced that popover is better so I change my position: let's go for popovers.

**Comment by luzpaz** [comment]
Is there an ETA on this ?

**Comment by auouymous** [comment]
@luzpaz #1293 will be merged once the injected extensions are fixed and a couple other minor fixes.

**Pull request closed without merging**
