### PR TITLE
fix NEW_LOCATION with same url, resulting in Already subscribed message

### PR DESCRIPTION
**Pull request by elelay**
when adding a new podcast.
Seen on https://www.youtube.com/watch?v=f9qOPA05fzE

### CODE REVIEW

**Comment by auouymous** [comment]
Does this work for you? It replaced the already subscribed error with another.

```
gpodder.feedcore.InvalidFeed: Could not parse feed: <unknown>:1:0: syntax error
```

**Comment by elelay** [comment]
> Does this work for you? It replaced the already subscribed error with another.
> 
> ```
> gpodder.feedcore.InvalidFeed: Could not parse feed: <unknown>:1:0: syntax error
> ```

now it's *the right* error ;-)

Subscribing to a single youtube video won't work: no autodiscovery and not a feed. The error already happened, but was hidden by the nonsensical "already subscribed".

**Comment by auouymous** [comment]
In that case, it LGTM. :)

The `<link itemprop="url" href="http://www.youtube.com/channel/UCiAInBL9kUzz1XRxk66v-gw">` tag was found in that video page and could be detected in feedcore.py to allow subscribing via a video page. I can do it when I get time, unless you do it sooner.

**Comment by elelay** [comment]
Please do it when you have time

**Pull request merged**
