### PR TITLE
Finalized translation

### PR DESCRIPTION
**Pull request by mrkaban**
Finalized translation

### CODE REVIEW

**Comment by elelay** [comment]
Great work!
Changing the readme wasn't necessary but I'll fix that on merge.

Can you have a look at all translations marked `#, fuzzy`? It's when xgettext thinks a new string to translate is close to an existing one, but it often gets it wrong. For instance here it confused the extension category with removal strategy:

```
#: bin/gpo:991
#, fuzzy
#| msgid "Strategy:"
msgid "Category:"
msgstr "Способ удаления:"
```

Best to review all fuzzy translations and fix them and remove the fuzzy line. gPodder won't use a translation marked fuzzy anyway.

Thanks!

**Comment by mrkaban** [comment]
I did not notice this line! Corrected, resend the request?

I did not know about the ban on changing readme.

**Comment by elelay** [comment]
> I did not notice this line! Corrected, resend the request?
> 

That's good, thanks! No need to resend the request.
Just push another commit with fixed fuzzy translations if you want.

**Comment by elelay** [comment]
Merging as is for now. If you have time, please open a new PR to fix remaining "fuzzy" items in the translation file.
Thanks!

**Comment by elelay** [comment]
If you have time and are interested, please subscribe to #518 to be notified of call for translation before each release.
It's usually only a handful of new / modified strings to translate.

**Pull request merged**
