### PR TITLE
Youtube live streaming support

### PR DESCRIPTION
**Pull request by auouymous**
Allows live streams to be streamed (but not downloaded) while live. The video player must support HLS m3u8 URLs (ffplay does). It adds a new `Video` setting to select HLS formats, and supports custom formats in `Edit config`.

### CODE REVIEW

**Comment by elelay** [comment]
Looks good.
I've added a fix to allow streaming videos if a custom video player was selected but the default audio player.
Do you agree?

**Comment by auouymous** [comment]
I don't understand what you said.

**Comment by elelay** [comment]
gPodder enables the **Stream** menu item only if the user has selected a player (vlc, ...).
episodes are streamed by executing the selected player with the download url.
audio episodes execute the audio player, video episodes the video player.

Before 8503fef the **Stream** menu item was disabled for video episodes (youtube live video) even if I selected VLC as video player because I kept the default audio player. Now gPodder looks at the video player for video episodes and the audio player for other kinds.

**Comment by auouymous** [comment]
Ah, I had a non-default audio player and the stream option does dim when changed to default. LGTM.

**Comment by elelay** [comment]
Let's merge, then!
Thanks,

**Pull request merged**
