### PR TITLE
Create config file with group/world permissions revoked

### PR DESCRIPTION
**Pull request by juergenhoetzel**
The config file contains sensible information (user/password).

Also remove unused import.

### CODE REVIEW

**Comment by auouymous** [comment]
I run my entire system with 077 and fully agree with this change. The patch looks good and appears to work fine, but will it cause any issues on Windows?

**Comment by juergenhoetzel** [comment]
> I run my entire system with 077 and fully agree with this change. The patch looks good and appears to work fine, but will it cause any issues on Windows?

Posix `umask` is also awailable on Windows: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/posix-umask?view=msvc-160

**Comment by elelay** [comment]
Thanks for the patch!

Tested on windows:
 - it doesn't crash
 - it doesn't change permissions.
 
withumask

I can't find information on python's os.umask, but testing results and this commit https://git.lclutz.de/ghstars/certbot-certbot/commit/50fa04ba0cb739eb0eafec2286cb08d9caae1b16 leads me to believe it's stubbed out on windows...

**Comment by elelay** [comment]
More direct test:
```
C:\Users\IEUser>C:\gpodder-3.10.17-portable\data\bin\python
Python 3.8.9 (default, Apr  3 2021, 09:29:25)  [GCC 10.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.umask(0)
0
>>> os.umask(0o077)
0
>>> os.umask(0)
0
```

Also cpython tests don't assert modified persmissions on windows https://github.com/python/cpython/blob/bb3e0c240bc60fe08d332ff5955d54197f79751c/Lib/test/test_os.py#L1582

@juergenhoetzel please add a simple comment that it's a noop on windows and let's merge, to improve it on other platforms.

**Comment by juergenhoetzel** [comment]
> @juergenhoetzel please add a simple comment that it's a noop on windows and let's merge, to improve it on other platforms.

Thank you for your research. I just amended the commit and added your suggestion.

**Comment by elelay** [comment]
Merged, thanks!

**Pull request merged**
