### PR TITLE
Italian language update

### PR DESCRIPTION
**Pull request by bovirus**
@elelay 

Please merge. Thanks.

### CODE REVIEW

**Comment by ciampix** [comment]
ahem ... did you see that there were already another Italian translation waiting for merge? #1678 ? Just to avoid wasting of time...

**Comment by bovirus** [comment]
@ciampix
Sorry but I just post the request of merge.

Note: basing on my experience I have a different vision about some strings.

Note1: I believe that in the sofwtare the typical verbs is 3rd person and not infinite.
Note2: for me the tranalsation should't a word to word translation but should use terms that are common for the language in software envorinment.

msgid "Show publishing statistics for subscriptions."
msgstr "Mostra le statistiche per le iscrizioni."
msgstr "Visualizza statistiche pubblicazione abbonamenti." (my proposal)
Comment: "Mostra" is oudated (and mostra is in a museum).
Subscritions are "SottsocrizionI" or "Abbonamenti" (not iscrizioni).
Is missing translation for "publishing"

msgid "Please provide at least 3 characters"
msgstr "Fornire almento 3 caratteri"
msgstr "Inserisci almeno 3 caratterI" (my proposal)
Note: "Fornire" is infinite and is out of context for the use in Italian.

msgid "Podcast Providers"
msgstr "Fornitori di podcast"
msgstr "Fornitori podcast"  (my proposal)
Comment: the article is not always necessary (in this string in english is not included).

msgid "Podcast Retrieve Progress"
msgstr "Avanzamento recupero podcast"
msgstr "Progresso recupero podcast"  (my proposal)
Comment: "Avanzamento" is unsual in this context. Is most used in this context "Progresso"

msgid "Light"
msgstr "Luminoso"
msgstr "Chiaro"  (my proposal)
Comment: about theme the opposite of Dark (Scuro) is "Chiaro" (not "Luminoso").
"Luminoso is not in context with theme.
"Luminoso" is used in female way for a sunny day.

msgid "Unexpected response from soundcloud: %r"
msgstr "Risposta inaspettata dal soundcloud: %r"
msgstr "Risposta non prevista dal soundcloud: %r"  (my proposal)
Comment: inaspettata in unusual. "Non prevista" is most used.

msgid "Sorry, no podcasts were found"
msgstr "Spiacenti, nessun podcast trovato"
msgstr "Nessun podcast trovato"  (my proposal)
"Spiacenti" is outdated as use. 

msgid "Download in progress..."
msgstr "Scaricamento in corso..."
msgstr "Download..."  (my proposal)
Comment: "Scaricamento" is not so common: Is most used "Download".
"..." and "in corso" have the same meaning. Is most used "..." then "in corso"

Thanks.

**Comment by ciampix** [comment]
I am not convinced by the changes you proposed, at all.
The timing is also suspicious: the criticisms came after it was pointed out that you posted the translation after another one had already been proposed.

**Comment by bovirus** [comment]
@ciampix
Sorry but I did'n't understand your negative point of view,.
I posted a lot of PR in last past (at least 10).
is not usal check PR befroe to post a language update if no one at now do it.
I'm so sorry that you are not agree about my motivated proposal of changes (please read carefully are proposal and not criticism - and I explain with detail the reason of changes).
I explain the raeson that is coming from many years in the world of professional translation about freeware/shareware software.
For me is not right to use in Italian terma as "Fornire" (infinite) or "Luminoso" because is unsual terms/verbs.
I will delete my PR.
Please consider that for me some of terms used are not right and out of usual context (you missied also a term..).
Then after that I will make a new PR to change them.

**Comment by bovirus** [comment]
Closed

**Comment by ciampix** [comment]
Sorry for my somewhat harsh reply. The thing is: you could have proposed a change to the aforementioned strings in my PR. At least that was what I would have done if you posted the PR before me. Anyway, I will try to analyze your suggestions and fix the most questionable issues. Your comments are welcome.

**Comment by ciampix** [comment]
Example 1:  "Visualizza" and "Mostra" are two different words, whose meaning is sightly different, see:

https://www.treccani.it/vocabolario/ricerca/visualizzare/ -> Display
https://www.treccani.it/vocabolario/ricerca/mostrare/ -> Show

https://www.wordreference.com/iten/visualizza
https://www.wordreference.com/iten/mostra

Example 2: "Note1: I believe that in the sofwtare the typical verbs is 3rd person and not infinite."
yes because of a bad habit of software translators that usually "italianize" the English dialogs. We are translators, and as you well explained earlier "tranalsation should't a word to word translation". In Italian, passive clauses are much more common than in English. So to create a translation that would ideally "sound" more familiar to an Italian, one has to rephrase the sentences a bit. English is more direct, they use much more "you do this" "you should do that" and so. In Italian that is considered a bit rude and one has to use the infinitive much more often. I also am well aware that I could be wrong of course. Linguist discussions like these tend to grow exponentially because every translator has also "a personal style, taste and / or point of view ...". So please concentrate only on the evident errors and not on the very questionable topics about stylistics opinions. Or at least present them as such, not errors. In that way suggestions are usually much more effective on me ... ;-)

**Comment by ciampix** [comment]
also ... "progresso" is almost a false friend in Italian. Using it for "progress" is incorrect. See as an example: "Il progresso della società non corrisponde sempre all'avanzamento dei lavori pubblici..." if you try switching the words, it sounds weird in Italian... I never saw "barra di progresso"... always "barra di avanzamento" even on Windows... ;-)

**Comment by ciampix** [comment]
also "most used" != "correct" btw

BUT

many suggestions you gave me are correct and I'm applying them to my PR, thanks!

**Comment by bovirus** [comment]
@ciampix 
Your reference are not right (it's generic not sofwtare reference).
The software translation use specific terms that are specific for software.
In th sofwtare the reference are Microsoft, Adobe, etc.
Technically all terms are good for Italian, but some terms are specific for sofwtare environment.
It's not true that it's normal to use infinite.
The right translation in menu for Apri (Open) and not Aprire, Salva (Save) not Salvare, etc.
In menu/ it's typically use strings without a lot of article/preposition.
Also you have to maintain the same style for same terms (and not change it):

You should analyze "Progress" not in a genric context (like publick works) but in software use.

Ex. Windows use "Visualizza"
image

Ex. Windows use Chiaro e Scurto for theme
image

Apply your changes and stop. Thanks.

**Comment by ciampix** [comment]
You are always late! ;-) Did you see before posting your answer that I already committed your suggestions (and mentioning your help - thanks btw)? ;-)

**Comment by elelay** [comment]
Glad you were able to sort it out and make an even better translation together.
@bovirus you closed your PR, preventing the headache of choosing between 2 translations on a language I know nothing of.
@ciampix you took @bovirus suggestions into kind consideration and merged some of them.

Too many translators is a nice problem to have ;-)
Maybe in the future write a comment telling you start doing the translation?

**Comment by ciampix** [comment]
Good point, I'll certainly do that!

**Pull request closed without merging**
