### PR TITLE
fixes #1000 with addition of FUNDING.yml site and fitting proper link…

### LINKED ISSUE #1000: github repo has no Donation link
while gpodder.net site has page for donations , developers coming rather from githab might be unaware of it.

e.g. in issue #886 they ask "Is there a link I can make a paypal donation through?" in punch line.

while having simple FUNDING.yml file in .github subdirectory can add it straight to repository pages.

### PR DESCRIPTION
**Pull request by silpol**
… inside

### CODE REVIEW

**Comment by silpol** [comment]
this PR has no affect on code but adds link to https://gpodder.net/contribute/ page in FUNDING.yml - lets help keep it running

**Comment by auouymous** [comment]
LGTM, but it would be better if it had a final newline.

@elelay Do you approve of a donation link for gpodder.net?

**Comment by elelay** [comment]
yes

**Comment by elelay** [comment]
Merged, thanks.
I'll add the newline myself

**Pull request merged**
