### PR TITLE
Add menu item to undownload downloaded episodes.

### LINKED ISSUE #864: Feature Request: add redownload dropdown menu option

### PR DESCRIPTION
**Pull request by auouymous**
Closes #864.

### CODE REVIEW

**Comment by elelay** [comment]
My concern is that a user will be puzzled by the choice between `Delete` and `Undownload`.
Maybe a better label? **Delete but/and keep New**?
Another option would be a popup to ask if marking new after deletion, but it would be annoying in the majority of cases (deleted because it's played or the user doesn't want to play it)...

**Comment by elelay** [comment]
Actually there is already a confirmation popup. Add a checkbox to **mark new to redownload*?

**Comment by auouymous** [comment]
Undownload is like an undo for download, the first four letters are even "Undo" and it uses the edit-undo icon. `Delete but keep new` doesn't make sense if an old/new checkbox appears on confirmation or if is_new won't be changed (see below). So it would need to be something like `Delete but keep episode`, which doesn't quite make sense as to what is happening. `Delete file, keep episode` might make more sense?

I changed the title and message for show_confirmation() when undownloading versus deleting, but I don't see how to add a checkbox to that dialog. Maybe it would be better to never mark as new, just change state to normal and leave it in its current is_new state. I originally marked it as new because I was using the mark(is_played) method to undelete it. The second commit makes it easy to remove the is_new line and have it still function properly. When redownloading a corrupt download, the episode will be marked new after it gets redowloaded, it wouldn't matter if it was new or old. When waiting to redownload for a better format, the user can manually mark it new for automatic download at next update or leave as old and manually redownload after a few hours.

**Comment by auouymous** [comment]
Rebased. The episode must be marked as new otherwise the feature is worthless for anyone who uses `View..Downloaded episodes` or `View..Unplayed episodes`, although the later requires an extra step if the episode is played because it gets removed and the view must be changed to undownload it. Anyone wanting the episode to be marked as played can perform the extra step after undownloading. But I imagine most would either immediately download it, or want it unplayed so the next update automatically downloads it.

> Undownload is like an undo for download, the first four letters are even "Undo" and it uses the edit-undo icon. Delete but keep new doesn't make sense if an old/new checkbox appears on confirmation or if is_new won't be changed (see below). So it would need to be something like Delete but keep episode, which doesn't quite make sense as to what is happening. Delete file, keep episode might make more sense?

Just waiting for a response to that.

**Comment by elelay** [comment]
I still think **undownload** is not going to help users and would would very much like to add a checkbox to the confirm dialog. This is what would feel natural to me.

**Comment by auouymous** [comment]
Replaced by #1284.

**Pull request closed without merging**
