### PR TITLE
Narrow channel dialog

### PR DESCRIPTION
**Pull request by tpikonen**
A rewrite of the channel dialog UI, allowing a narrower width, and a 'modern' look.

I'm on the fence on whether the dialog should have 'Cancel' and 'Save' buttons instead of just 'Close'. Probably, but I did not add them yet.

### CODE REVIEW

**Comment by auouymous** [comment]
It looks good...

I mostly use the channel dialog to set sections and filters. Now I am forced to scroll to set the section. Some podcasts have really long descriptions, is it possible to clip the description to a couple lines and add a show more button to see the full description? The update error is appended to description, and if clipped, it might need its own fully visible label in the dialog (with an error icon).

Is it possible to add non-scrolling notebook-like buttons along the top that jump to description, settings, advanced settings or extensions? My trackpad lacks scrolling and the dialog doesn't scroll with arrow keys, forcing me to reach for the scroll keys on edge of keyboard or the mouse. A button that jumps to settings would be an extra step but not that big of a deal, and the description wouldn't need clipping.

Please remove the bogus tab stops on the container widgets, they require two tab presses for most widgets.

It also broke the filter extension (and maybe others) because you removed the notebook they add pages to. Do you propose extensions append to the end of the scroll forever window?

Close button has no margin around it.

**Comment by auouymous** [comment]
Please don't override the GtkNotebook theme, maybe it looks good on your system with your theme but it is unusable on mine.

The Cancel and Ok buttons still don't have a margin.

I like the Cancel button but it doesn't work for the filter extension, and I doubt it is possible. Should the filter extension have a label informing users that changes are final?

Should the section combo box and new section button have a gap between each other?

The username and password labels have no gap between the input box.

The upper settings look good but the username and password don't. The box uses the same background color as the inputs, and they stand out and look nicer on the window's background color. And hovering or clicking the inputs changes the row inside the box to the highlight background color. This is fine for switches and combo boxes but makes entering text harder. I realize the row can be clicked to focus the input box, and that might make touch easier, but it worsens the usability for others.

Do you think the re-filter button should have a horizontal separator above it so the new label better associates with the button?

**Comment by auouymous** [comment]
The current dialog centers on parent, but this patch does not, even though it should. Do you know what could have broken that?

The channel dialog should also save its size and position. It went from a landscape window to a portrait window which makes the description a little harder to read, requires scrolling to see the URL and reduces the visible content in filter input boxes. I would set my window manager to remember the size but the dialog has a different title for each channel. Using a fixed dialog title would work, except for users on Windows.

**Comment by tpikonen** [comment]
Thanks for the comments @auouymous, I think I addressed all of them in the latest push, except saving the dialog size and position. I think that's a separate PR, if we decide to do that. The dialog is now always called 'Channel Editor', if that helps.

I run the default GTK theme, and the white ListBoxRows looked pretty bad on white Notebook background. I removed the frame around the rows, which makes the rows blend into the background when not highlighted and looks better.

**Comment by auouymous** [comment]
LGTM, @elelay do you approve?

I think we should save and restore the window size and position. There are users who depend on it, and I'm sure they'd appreciate it now that this dialog is narrower.

**Comment by elelay** [comment]
Looks good to me except the description is not selectable. This must be fixed (I'd use a text area for that).

**Comment by auouymous** [comment]
Ah missed that, the update error was added to the description's textarea so it would be copyable. A selectable property like the two URLs have should be good enough for description.

**Comment by auouymous** [comment]
Another issue is the website URL that is no longer selectable.

And the old username/password entries were aligned to each other, is that not possible with the new layout?

**Comment by tpikonen** [comment]
Here you are. Let me know if there's anything still to be fixed. If not, I'll squash this to something more reasonable.

**Comment by elelay** [comment]
looks good to me, thanks!

**Comment by tpikonen** [comment]
Squashed and rebased to master.

**Comment by auouymous** [comment]
LGTM. Does it save and restore the dialog position? If done in another PR, it would be nice if that PR was ready before this is merged.

**Comment by elelay** [comment]
See 834106e67c6ba379c6b0b1b3fb666c037c6e3888
it's good to save/restore positions for windows and macOS

**Comment by auouymous** [comment]
Does the website link work for you? The "Open Link" menu item does nothing and clicking the link places a cursor on it and changes its color to from blue to white. Double-clicking selects text within the URL and then right-clicking opens a "text" context menu to select all or copy.

**Comment by auouymous** [comment]
The About dialog links also don't work but #1095 fixes them and could be applied here as well.

**Comment by auouymous** [comment]
```patch
From ab2219cb95fd2b9aa9545ab1cb77b59db16b0b31 Mon Sep 17 00:00:00 2001
From: auouymous <au@qzx.com>
Date: Sat, 17 Jul 2021 21:50:20 -0600
Subject: [PATCH] Save and restore channel dialog state.

---
 src/gpodder/config.py                | 5 +++++
 src/gpodder/gtkui/desktop/channel.py | 2 ++
 2 files changed, 7 insertions(+)

diff --git a/src/gpodder/config.py b/src/gpodder/config.py
index 45381bc0..f92189c8 100644
--- a/src/gpodder/config.py
+++ b/src/gpodder/config.py
@@ -130,6 +130,11 @@ defaults = {
                     'height': -1,
                     'x': -1, 'y': -1, 'maximized': False,
                 },
+                'channel_editor': {
+                    'width': -1,
+                    'height': -1,
+                    'x': -1, 'y': -1, 'maximized': False,
+                },
                 'episode_selector': {
                     'width': 600,
                     'height': 400,
diff --git a/src/gpodder/gtkui/desktop/channel.py b/src/gpodder/gtkui/desktop/channel.py
index ad252857..ea2d1238 100644
--- a/src/gpodder/gtkui/desktop/channel.py
+++ b/src/gpodder/gtkui/desktop/channel.py
@@ -98,6 +98,8 @@ class gPodderChannel(BuilderWidget):
         self.imgCoverEventBox.connect('button-press-event',
                 self.on_cover_popup_menu)
 
+        self._config.connect_gtk_window(self.gPodderChannel, 'channel_editor', True)
+
         gpodder.user_extensions.on_ui_object_available('channel-gtk', self)
 
         result = gpodder.user_extensions.on_channel_settings(self.channel)
-- 
2.31.1

```

**Comment by auouymous** [comment]
These two patches should resolve all issues and allow this to be merged. @elelay Should we do it now or wait until after release?

```patch
From a0888b0eeb78789a6e6f9942824726c21abd266a Mon Sep 17 00:00:00 2001
From: auouymous <au@qzx.com>
Date: Sat, 17 Jul 2021 22:21:16 -0600
Subject: [PATCH] Fix link in channel dialog by connecting signal and opening
 website.

---
 src/gpodder/gtkui/desktop/channel.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/gpodder/gtkui/desktop/channel.py b/src/gpodder/gtkui/desktop/channel.py
index 9e1fb388..1183139a 100644
--- a/src/gpodder/gtkui/desktop/channel.py
+++ b/src/gpodder/gtkui/desktop/channel.py
@@ -67,6 +67,7 @@ class gPodderChannel(BuilderWidget):
         self.website_label.set_markup('<a href="{}">{}</a>'.format(
             self.channel.link, self.channel.link)
             if self.channel.link else '')
+        self.website_label.connect('activate-link', lambda label, url: util.open_website(url))
 
         if self.channel.auth_username:
             self.FeedUsername.set_text(self.channel.auth_username)
-- 
2.31.1

```

**Comment by elelay** [comment]
@auouymous links are working in podcast settings and in about dialog without your fix.
You use activate-link to override the default, whatever it does...
https://developer.gnome.org/gtk3/stable/GtkLabel.html#id-1.3.8.2.10.9

On my machine links are opened in the current firefox window. I have the `BROWSER=firefox` environment variable set.

Feel free to commit the *Save and restore channel dialog state.* on this branche and merge before release.

**Comment by auouymous** [comment]
@elelay Do the about links work on Mac and Windows for you? I set BROWSER=w3m with patch disabled and the links still don't work in Linux.

**Comment by elelay** [comment]
They work on macOS.
on Linux(Archlinux) I have gtk 3.24.30-1

**Comment by elelay** [comment]
Seems to call [gtk_show_uri_on_window](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkshow.c#L159) by default

**Comment by elelay** [comment]
You might want to try `http://lazka.github.io/pgi-docs/#Gtk-3.0/functions.html#Gtk.show_uri_on_window`:
From a python shell
```
>>> import gi
>>> from gi.repository import Gtk
<stdin>:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>>> Gtk.show_uri_on_window(None, 'https://gpodder.github.io', 0)
True
```

(and a tab opens)

**Comment by auouymous** [comment]
I have 3.24.29 on Linux and the Windows artifact I installed has 3.24.30, and I'll be testing the patched artifact tomorrow to verify it fixed the problem there. Did you set BROWSER on Mac? Does it work on Linux without BROWSER? We shouldn't require environment variables for features to work.

From that https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkshow.c#L159:

> The uri must be of a form understood by GIO (i.e. you  * need to install gvfs to get support for uri schemes such as http://  * or ftp://, as only local files are handled by GIO itself)

I don't have gvfs installed and neither does the Windows build.

**Comment by auouymous** [comment]
```
>>> Gtk.show_uri_on_window(None, 'https://gpodder.github.io', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
gi.repository.GLib.Error: g-io-error-quark: Operation not supported (15)
```

**Comment by elelay** [comment]
Ah, that's it then: gvfs is indeed installed on my machine. It's not installed on macOS but links work.
I can't check on windows right now.
So go for your patches :+1: to podcast and about dialogs. Maybe search for a href markup elsewhere?

**Comment by auouymous** [comment]
> Maybe search for a href markup elsewhere?

What?

**Comment by elelay** [comment]
> > Maybe search for a href markup elsewhere?

I meant `git grep href= src` to look for any other use of hyperlinks in label markup. But you already got them all.

**Pull request merged**
