### PR TITLE
Change desciption from Run Command on Download

### PR DESCRIPTION
**Pull request by TZocker**
Like 
https://gpodder.github.io/docs/extensions/commandondownload.html

I think is't better than to explain it with itself.

greetz

### CODE REVIEW

**Comment by elelay** [comment]
Thanks,
You'll want to also modify the source code, otherwise the translation will simply be missing.
1. change the key in `share/gpodder/extensions/command_on_download.py` line 19
2. run make messages
3. ensure your translation is still there in de.po

**Comment by TZocker** [comment]
#https://github.com/gpodder/gpodder/compare/master...TZocker:patch-4

**Comment by TZocker** [comment]
#6a94d6dad37c6a57fab656cafaa006b7ff0183a1

**Comment by elelay** [comment]
Good!
Next time, please also commit all modified po (produced by running make messages).
(I've done it in ea9f0e57).

**Comment by TZocker** [comment]
thx elelay but how?

**Comment by elelay** [comment]
> thx elelay but how?
run `make messages` in the gpodder clone directory after modifying source code.

**Pull request merged**
