### PR TITLE
Use the requests package for all http requests

### PR DESCRIPTION
**Pull request by elelay**

### CODE REVIEW

**Comment by auouymous** [comment]
src/gpodder/feedcore.py:192:56: E226 missing whitespace around arithmetic operator

I applied these patches and they seem to work with limited testing, I'll let you know if they break in the next few days. Do you know the requests package has at least 6 dependencies? This one change doubles the minimum dependencies needed to run gpodder.

**Comment by elelay** [comment]
Thanks for your testing and feedback: it's good to know nothing is broken (yet)!

Yes, it adds dependencies but urllib is lagging in features for the core thing in gPodder (http).
requests will let us move forward and solve past and upcomming struggles (without reimplementing it ourself on top of urllib).

requests is a thin wrapper around urllib3. It does the right thing for:
 - redirections (understands 308 redirect)
 - auth (https://github.com/gpodder/gpodder/issues/285#issuecomment-447648138)
 - compressed transfer (#836)
 - connection pooling (not used yet)

It depends on:
 - chardet for guessing the encoding when it's not specified (handy in autodiscovery mode when looking for links to the feed in html page)
 - idna for correctly handling internationalized domain names (apparently broken in python standard library, I don't know anything about that)
 - urllib3 for the actual http(s) implementation
 - certifi for a bundle of ssl trust roots (I already use it for the windows port)

Optional dependencies:
 - PySocks for SOCKS proxies (not yet decided if I include it in packages)
 - brotlipy to support brotli compression

I'm not concerned about those dependencies because urllib3 is already used in recent versions of pip, so it's likely already installed on Linux and the size of python deps is dwarfed by the whole gtk3 stack in macOS/Windows packages.

The next area I'll port to requests is download.py.

**Comment by auouymous** [comment]
I know this is needed. Gentoo's urllib3 also requires PySocks, pyopenssl and cryptography, is that not the case for the windows/mac builds?

**Comment by elelay** [comment]
Example internationalized domain name: https://日本語.jp/
It fails in master branch with encoding error and still fails in request branch, but with invalid html (expected because it's not a feed, but it was able to be downloaded)...

**Comment by elelay** [comment]
> Gentoo's urllib3 also requires PySocks, pyopenssl and cryptography, is that not the case for the windows/mac builds?

AFAICT pyopenssl and cryptography are only needed to enable SNI verification in python2 (https://github.com/urllib3/urllib3/blob/eee53a69e1af019da18635d6974f893308db0ada/src/urllib3/contrib/pyopenssl.py and https://github.com/psf/requests/blob/251f73f65d46ff5de64b8ae2e6c6fe38c1a28808/requests/__init__.py#L96).

Pysocks should indeed be installed for SOCKS proxy support

**Comment by elelay** [comment]
I overlooked requests's encoding detection: it doesn't use chardet automatically (one has to call response.apparent_encoding to get it) and falls back to ISO-8859-1 if content-type is `text/*` and the server doesn't specify the charset.

So all my happy changes from shady decode to response.text must be reconsidered.

**Comment by elelay** [comment]
Fixed for feedcore in d59bba5, but escapist.py, youtube.py, etc. need to be fixed

**Comment by auouymous** [comment]
Downloading youtube episodes works fine, but subscribing fails.
https://www.youtube.com/c/securitynow

```
1595530245.964432 [gpodder.gtkui.main] ERROR: Subscription error: 'str' object has no attribute 'headers'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gpodder/gtkui/main.py", line 2471, in thread_proc
    max_episodes=self.config.max_episodes_per_feed)
  File "/usr/lib/python3.7/site-packages/gpodder/model.py", line 1389, in load_podcast
    max_episodes)
  File "/usr/lib/python3.7/site-packages/gpodder/model.py", line 977, in load
    tmp.update(max_episodes)
  File "/usr/lib/python3.7/site-packages/gpodder/model.py", line 1153, in update
    result = self.feed_fetcher.fetch_channel(self, max_episodes)
  File "/usr/lib/python3.7/site-packages/gpodder/model.py", line 207, in fetch_channel
    return self.fetch(url, channel.http_etag, channel.http_last_modified, max_episodes=max_episodes)
  File "/usr/lib/python3.7/site-packages/gpodder/feedcore.py", line 197, in fetch
    ad.feed(util.response_text(stream.text))
  File "/usr/lib/python3.7/site-packages/gpodder/util.py", line 2206, in response_text
    if 'charset=' in response.headers.get('content-type'):
AttributeError: 'str' object has no attribute 'headers'
```

**Comment by elelay** [comment]
you're right, thanks!
It's fixed now

**Comment by elelay** [comment]
@auouymous I have further work to push (unittests, fix lint, retry rss download) but it's not quite ready yet...

**Comment by auouymous** [comment]
@elelay Okay, all patches are working fine so far.

**Comment by auouymous** [comment]
The isort -rc removal causes the following warnings for me.

```
WARNING: Unable to parse file share due to [Errno 21] Is a directory: '/home/github-auouymous/gpodder/share'
WARNING: Unable to parse file src/gpodder due to [Errno 21] Is a directory: '/home/github-auouymous/gpodder/src/gpodder'
WARNING: Unable to parse file tools due to [Errno 21] Is a directory: '/home/github-auouymous/gpodder/tools'
```

**Comment by elelay** [comment]
Hi, please try with isort >= 5.0.0.

**Comment by auouymous** [comment]
Gentoo doesn't have 5.0+ yet and the ebuild for 4.3.21 won't successfully build the 5.0 branch.

**Comment by auouymous** [comment]
> Gentoo doesn't have 5.0+ yet and the ebuild for 4.3.21 won't successfully build the 5.0 branch.

@elelay Gentoo now has isort 5.7 if you want to revert 2f6ad17.

**Comment by elelay** [comment]
@auouymous done, thanks

**Pull request merged**
