### PR TITLE
[shebang] Change /usr/bin/python -> /usr/bin/env python3

### PR DESCRIPTION
**Pull request by thp**
This should fix "unusual interpreter" Lintian warnings here:
https://udd.debian.org/lintian/?packages=gpodder

### CODE REVIEW

**Comment by thp** [comment]
(not all of these scripts need or should have a shebang line to begin with, but this is the least intrusive change)

**Comment by auouymous** [comment]
We might as well remove the shebang now if not needed.

Need shebang:
- share/gpodder/examples/gpodder_mark_played.py
- src/gpodder/minidb.py

Don't need shebang:
- share/gpodder/extensions/rm_ogg_cover.py
- share/gpodder/extensions/rockbox_convert2mp4.py
- share/gpodder/extensions/tagging.py
- src/gpodder/dbusproxy.py
- src/gpodder/gtkui/widgets.py
- src/gpodder/my.py
- src/gpodder/plugins/soundcloud.py

**Comment by auouymous** [comment]
Thanks for the fixes.

**Review by tmancill — COMMENTED** [review]
Thanks!

**Pull request merged**
