### PR TITLE
without the ActivateTab, no progress bar (extended)

### PR DESCRIPTION
**Pull request by elelay**
Further work on #1209 
Still to be tested before merge

### CODE REVIEW

**Comment by arne182** [comment]
Excellent. Thanks for integrating my change.

**Comment by auouymous** [comment]
Code looks fine. I tested on a Win10 machine today and I don't think it works. I enabled the extension and downloaded an episode but nothing happened on the taskbar.

**Comment by elelay** [comment]
> I enabled the extension and downloaded an episode but nothing happened on the taskbar.
do you use a "classic" theme? It doesn't show with it but with modern theme.
Also gPodder might need to restart before it works

**Comment by auouymous** [comment]
By classic do you mean what win95 looked like? It wasn't my computer so I don't know what theme it had, but its taskbar looked like https://i.insider.com/55b7aebbdd08958f7f8b4600?width=2160 (without that white search box). I closed and killed gpodder (in task manager) at least a dozen times, so pretty sure it was started with the extension.

If it works for you on win10 then it should be good to go, because that machine is heavily configured and maybe something is disabled.

**Comment by elelay** [comment]
> By classic do you mean what win95 looked like? It wasn't my computer so I don't know what theme it had, but its taskbar looked like https://i.insider.com/55b7aebbdd08958f7f8b4600?width=2160 (without that white search box). I closed and killed gpodder (in task manager) at least a dozen times, so pretty sure it was started with the extension.
> 

yes it is the same theme I have. No idea why it didn't work on this system...

**Pull request merged**
