### PR TITLE
Embed subtitles to videos downloaded with the youtube-dl extension

### LINKED ISSUE #379: [Wish] Subtitles/Transcript for YouTube videos
I would like to download the transcript/subtitles from YouTube videos with my subscription.

Thanks.

### PR DESCRIPTION
**Pull request by tpikonen**
Fixes #379.

There are some problems with the youtube.py and youtube-dl extension interaction, plus this breaks downloads if ffmpeg is not installed, so setting as draft for now.

### CODE REVIEW

**Comment by tpikonen** [comment]
Rebased and adapted to current master.

**Comment by tpikonen** [comment]
So, now that #1382 is merged, this reduced to just a couple of lines. Subtitle embedding works fine when ffmpeg is installed, and even previews work with non-fragment downloads in youtube.

When ffmpeg is not installed, this probably breaks most youtube-dl downloads. The solution is to either detect if ffmpeg is installed, or to put this behind a config var. Any ideas on which one is better?

**Comment by auouymous** [comment]
The extension should add a setting that defaults to off to avoid putting subtitles in downloads. When enabled, it should use util.find_command('ffmpeg') and display an error message before disabling the setting if not found.

**Comment by tpikonen** [comment]
Rebased to master and added a checkbox to enable subtitle embedding in the youtube-dl preferences page. If ffmpeg is not found, prevent enabling and show an infobox to inform the user about the requirement.

**Comment by auouymous** [comment]
The checkbox and separator should sit below the note that is specifically for the manage-downloads checkbox.

**Comment by tpikonen** [comment]
Ah, thanks for noticing. Fixed now.

**Comment by auouymous** [comment]
Thanks for the improvement.

**Pull request merged**
